Algoritmo "ATIVIDADE G"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2025
Var
   // Seção de Declarações das variáveis
   num1,num2,num3,num4:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   escreval("digite um número ")
   leia(num1)
   escreval("digite um outro valor ")
   leia(num2)
   escreval("digite mais um ")
   leia(num3)
   escreval("digite um número novamente ")
   leia(num4)

   se (num1 %2=0) entao
      escreval(num1, " esse número é divisivel por 2")

   senao
      escreval(num1 , " esse número não é divisivel por 2")
   fimse

   se (num1 %3=0) entao
      escreval(num1 ," esse número é divisivel por 3")

   senao
      escreval(num1 ," esse número não é divisivel por 3 ")

   fimse

   se (num2 %2=0) entao
      escreval(num2, " esse número é divisivel por 2")

   senao
      escreval(num2, "esse número não é divisivel por 2")
   fimse

   se (num2 %3=0) entao
      escreval(num2 ," esse número é divisivel por 3")

   senao
      escreval(num2 ," esse número não é divisivel por 3 ")

   fimse
   se (num3 %2=0) entao
      escreval(num3, " esse número é divisivel por 2")

   senao
      escreval(num3, "esse número não é divisivel por 2")
   fimse

   se (num3 %3=0) entao
      escreval(num3 ," esse número é divisivel por 3")

   senao
      escreval(num3 ," esse número não é divisivel por 3 ")

   fimse
   
    se (num4 %2=0) entao
      escreval(num4, " esse número é divisivel por 2")

   senao
      escreval(num4, " esse número não é divisivel por 2")
   fimse

   se (num4 %3=0) entao
      escreval(num4 ," esse número é divisivel por 3")

   senao
      escreval(num4 ," esse número não é divisivel por 3 ")

   fimse
















Fimalgoritmo