Algoritmo "ATIVIDADE J, CONVETER "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo
// Data atual  : 06/04/2025
Var
// Seção de Declarações das variáveis
contador:inteiro
c,f: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...


para contador de 10 ate 100 passo 10 faca

c<- contador

f<- (9*c+160)/5
escreval(contador," Celsius convertendo para Fahreheit fica ",f)

fimpara


Fimalgoritmo