Algoritmo "Atividade de lógica, atividade 03 "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaja
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo
// Data atual  : 26/03/2025
Var
   // Seção de Declarações das variáveis
   contador: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contador<- 1
   escreva(" Todos os número divisiveis por 4 até o 200 ")
   escreval("")
   repita
      se contador %4 =0 entao
         escreval(contador)
      fimse
      contador<- contador + 1
   ate contador>200



Fimalgoritmo