Algoritmo "Atividade A, conveter"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis 
f,c:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval(" vamos colocar a temperatura de Celsius para Fahrenheit")

escreva(" digite a temperatura em Celsius ")
leia(c)


f<- (9*c + 160)/5

escreval("a temperatura em Fahrenheit vai ficar ",f," graus")


Fimalgoritmo