Algoritmo "Atividade C, Volume da lata"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis 
raio,volume,altura: real



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval(" vamos descobrir o volume da lata de oléo ")

escreva("digite o raio :")
leia(raio)

escreva("digite o a altura da lata ")
leia(altura)

volume<- pi*(raio*raio)*altura

escreval(" o volume da lata é ",volume :2:2)





Fimalgoritmo