Algoritmo "ATIVIDADE C, pares de 1 até o 50 enquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2025
Var
   // Seção de Declarações das variáveis
   contador,soma:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contador<- 0

   enquanto contador<500 faca

      contador<- contador+2
      
      soma<- soma + contador

      escreval(contador)
      
      

  fimenquanto

Fimalgoritmo