Algoritmo "ATIVIDADE B, somador total"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2025
Var
   // Seção de Declarações das variáveis
   contador,soma:real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   enquanto contador<100 faca

      contador<- contador+1

      soma<- soma+contador

      escreval(soma)

   fimenquanto





Fimalgoritmo