Algoritmo "ATIVIDA G, fibonacci"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2025
Var
// Seção de Declarações das variáveis 
termo1,termo2, contador,proximo: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  termo1 <- 1
   termo2 <- 1
   contador <- 3

   escreval("Vamos fazer o Fibonacci até o 15º termo:")
   escreval(termo1)
   escreval(termo2)

   enquanto contador <= 15 faca
      proximo <- termo1 + termo2
      escreval(proximo)

      termo1 <- termo2
      termo2 <- proximo

      contador <- contador + 1
   fimenquanto






Fimalgoritmo