Algoritmo "ATIVIDADE D "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2025
Var
   // Seção de Declarações das variáveis
   contador: inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   enquanto contador<20 faca
      contador<- contador+1
      se (contador % 2) <> 0 entao
      escreval(contador)
      fimse


   fimenquanto

Fimalgoritmo