Algoritmo "Atividade B, conveter"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis
f,c:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreval(" vamos colocar a temperatura de Fahrenheit para Celsius")

escreva(" digite a temperatura em Fahrenheit ")
leia(f)


c<- (f- 32) * (5/9)

escreval("a temperatura em Graus Celsius é " , c)


Fimalgoritmo