Algoritmo "ATIVIDADE B tabuada,pag 66"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis 
contador:inteiro
num,vezes:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval(" digite um número :")
leia(num)

para contador de 1 ate 10 faca

vezes<- num*contador

escreval("o número ", num ," X ",contador, " = ", vezes)

fimpara


Fimalgoritmo