Algoritmo "Atividade L "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis 
A,B,C,soma: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval("digite qual o valor do A :")
leia(A)
escreval("digite o valor do B :")
leia(B)
escreval("digite o valor do C ")
leia(C)
soma<- (A*A)+(B*B)+(C*C)

escreva("Soma dos quadrados dos valores lidos é ",soma:2:2)


Fimalgoritmo