Algoritmo "Atividade F, Mudar A e B"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis 
A,B,mudar:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("mudar os valores da A e B ")

escreva("digite um valor Para A :")
leia(A)

escreva("digite um valor para B :  ")
leia(B)

mudar<- B
B<- A
A<- mudar


escreval(" o valor A é  " , A ," o valor B é ", B)


Fimalgoritmo