Algoritmo "ATIVIDADE H, CONVETER "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2025
Var
// Seção de Declarações das variáveis 
contador:inteiro
c,f: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

contador <- 10

   enquanto contador <= 100 faca
      c <- contador
      f <- (9 * c + 160) / 5
      escreval(contador, " Celsius convertendo para Fahrenheit fica ", f)
      contador <- contador + 10
   fimenquanto



Fimalgoritmo