Algoritmo "ATIVIDADE K"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2025
Var
   // Seção de Declarações das variáveis
   num:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval(" digite um número  menor que 3")
   leia(num)

   se num<3 entao
      escreval(" o número é ", num)

   senao
      escreval(" o valor precisa ser menor que 3 ")
   fimse


fimalgoritmo
