Algoritmo "ATIVIDADE I, par ou impar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    :  Gustavo
// Data atual  : 05/04/2025
Var
   // Seção de Declarações das variáveis
   num:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval(" digite um número e vamos descobrir se ele é par ou impar")
   leia(num)

   se (num%2= 0 ) entao
      escreval(num, " esse número é par ")

   senao
      escreval(num, " esse número é impar ")
   fimse


Fimalgoritmo