Algoritmo "Atividade I,  A e B"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
   // Seção de Declarações das variáveis
   a,b,resultado: real


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval(" digite um valor : ")
   leia(a)
   escreval(" digite outro valor ")
   leia(b)
   
   resultado<- (a-b)^2
   
   

   
   escreva(" díferença do quadrado de ", a , " e ", b , " é ",resultado)

Fimalgoritmo