Algoritmo "ATIVIDADE J, entre 1 a 9"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2025
Var
   // Seção de Declarações das variáveis
   num:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval(" digite um número entre 1 a 9 ")
   leia(num)

   se (num>=1) e (num<=9) entao
      escreval(" O valor está na faixa permitida ")

   senao
      escreval ( "o valor está fora da faixa permitida ")
   fimse



Fimalgoritmo