Algoritmo "atividade H, volume de uma caixa retangular "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis 
volume,compri,largura,altura:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreval(" me informe o comprimento da caixa :")
leia(compri)

escreval(" Me informe a largura :")
leia(largura)

escreval(" qual a altura : ")
leia(altura)

volume<- compri*largura*altura

escreva(" O volume é ",volume)



Fimalgoritmo