Algoritmo "Atividade G "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis 
A,B,C,D,soma,multi:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("digite o primeiro valor : ")
leia(A)

escreva("digite o segundo valor : ")
leia(B)

escreva("digite o terceiro valor : ")
leia(C)

escreva("digite o último valor :")
leia(D)

soma<- A + B
multi<- A * B
escreval(" A + B =  ", soma)
escreval("A * B = ", multi)

soma<- A + C
multi<- A * C
escreval("A + C =  ", soma)
escreval(" A * C =  " ,multi)


soma<- A + D
multi<- A * D
escreval(" A + D =  ",soma)
escreval("A * D =  ",multi)


soma<- B + C
multi<- B * C
escreval(" B + C =  ",soma)
escreval(" B * C =  ",multi)


soma<- B + D
multi<- B * D
escreval(" B + D =  ", soma )
escreval("B * D = ", multi )

soma<- C + D
multi<- C * D
escreval(" C + D = " , soma)
escreval(" C * D = " , multi)










Fimalgoritmo