Algoritmo "ATIVIDADE A , pag 66"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis
contador:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


para contador de 15 ate 200 faca


escreval(contador*contador)

fimpara


Fimalgoritmo