Algoritmo "Atividade K, converter para real"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis
cotacao,dinheiro,money:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval(" Quantos reais você tem  :")
leia(dinheiro)

escreva("digite a cotação do dolar atualmente ")
leia(cotacao)

money<- dinheiro / cotacao

escreval(" convertendo vai ter  Dollars R$",money:2:2)



Fimalgoritmo