Algoritmo "ATIVIDADE D, pares de 1 até o 500"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 06/04/2025
Var
   // Seção de Declarações das variáveis
   contador,soma:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...


   para contador de 1 ate 500 passo 2 faca

      contador<- contador+1

      soma<- soma + contador

      escreval(soma)



   fimpara

Fimalgoritmo