Algoritmo "Atividade M  "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Henrique de Souza santos
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis
A,B,C,soma,quadrado: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreval("digite qual o valor do A :")
leia(A)
escreval("digite o valor do B :")
leia(B)
escreval("digite o valor do C ")
leia(C)
soma<- A+B+C
quadrado<- soma*soma

escreva("O quadrado da soma  dos  valores lidos é ",quadrado:2:2)


Fimalgoritmo