Algoritmo "ATIVIDADE B "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/04/2025
Var
   // Seção de Declarações das variáveis
   num:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("digite um número : ")
   leia(num)

   se num<0 entao
      num<- num*-1

      escreval(" o número é " , num)

   senao
      escreval(" o número é :", num)
   fimse


Fimalgoritmo