Algoritmo "ATIVIDADE E , PAG 66"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis 

contador:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para contador de 1 ate 20 faca

se (contador %2 )<>0  entao
escreval( contador )
fimse

fimpara


Fimalgoritmo