Algoritmo "ATIVIDADE F, dividir por 4 "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2025
Var
// Seção de Declarações das variáveis 
contador:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

para contador de 1 ate 200 faca
se (contador %4)=0 entao
escreval(contador)
fimse

fimpara


Fimalgoritmo