Algoritmo "ATIVIDADE A, tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/04/2025
Var
// Seção de Declarações das variáveis 
num,contador,vezes:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreval(" digite um número para fazemos a tabuada  :")
leia(num)

enquanto contador<10 faca
contador<- contador+1


vezes<- num* contador

escreval(num , " X ",contador, " = ",vezes)

fimenquanto


Fimalgoritmo