Algoritmo "Atividade J, converter"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/04/2025
Var
// Seção de Declarações das variáveis 
cotacao,dinheiro,money:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval(" Quantos dólals você tem  :")
leia(money)

escreva("digite a cotação do dolar atualmente ")
leia(cotacao)

dinheiro<- cotacao * money

escreval(" você tem isso de dollar R$:",money ," convertendo vai ter ",dinheiro)



Fimalgoritmo