Algoritmo "ATIVIDADE  G "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/04/2025
Var
   // Seção de Declarações das variáveis
   base,resultado,expoente,i:inteiro


Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   base<- 3

   para expoente de 0 ate 15 faca
      resultado<- 1

      para i de 1 ate expoente faca
         resultado<- resultado * base
      fimpara

      escreval(" 3 elevado a ", expoente , "=", resultado)
   fimpara


Fimalgoritmo