Algoritmo "Exercicios Do Manzano 01,quadrado 15 a 200 "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jaja
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gustavo Henrique De Souza
// Data atual  : 26/03/2025
Var
// Seção de Declarações das variáveis 
contador: inteiro
resultado:inteiro




Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Quadrados de 15 a 200")
contador<- 15
repita
resultado<- contador*contador
escreval(" o quadrado do " ,contador, " é ", resultado)
contador<- contador+1

ate contador>200



Fimalgoritmo