Algoritmo "Extra 3,1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/04/2025
Var
// Seção de Declarações das variáveis 
A,B,C,D,P,S:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval(" digite o valor A : ")
leia(A)
escreval("digite o valor B")
leia(B)
escreval(" digite o valor do C")
leia(C)
escreval("digite o valor D")
leia(D)

p<- A*C
s<- B+D

escrevaL(" o resultado do produto  de A e C é ", p)
escreval("o resultado da soma do B e D é  ", s)





Fimalgoritmo