Algoritmo "Extra 3,2 "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/04/2025
Var
// Seção de Declarações das variáveis 
SM,PR,NS:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreval(" digite o seu salario : ")
leia(SM)
escreval("digite o reajuste em porcentagem  : ")
leia(PR)

NS<- SM+(SM* PR / 100)

escreval(" o Seu antigo salário era  ", SM ," Agora seu sálário é  ", NS)


Fimalgoritmo