Algoritmo "Fatorias impares "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/04/2025
Var
   // Seção de Declarações das variáveis
   contador,fatorial,contador2:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...


   para contador de 1 ate 10 passo 2 faca
      fatorial<- 1
      para contador2 de 1 ate contador faca
         fatorial<- fatorial*contador2
      fimpara

      escreval(fatorial)

   fimpara


Fimalgoritmo