Algoritmo "tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 02/04/2025
Var
// Seção de Declarações das variáveis 
contador,num,vezes:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("digite um número")
leia(num)

para contador de 1 ate 10 passo 1    faca
vezes<- num*contador

escreval(num,"*",contador,"=",vezes)

fimpara


Fimalgoritmo